/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
         backgroundImage: {
        'us': "url('/src/assets/US.svg')",
        'eu': "url('/src/assets/Europe.svg')",
        'uk': "url('/src/assets/UK.svg')",
        'tr': "url('/src/assets/TR.svg')",
        'myr': "url('/src/assets/MYR.svg')",
        'thb': "url('/src/assets/THB.svg')",
        'hkd': "url('/src/assets/HKD.svg')",
        'rub': "url('/src/assets/RUB.svg')",
        'azn': "url('/src/assets/AZN.svg')",
        'amd': "url('/src/assets/AMD.svg')",
        'gel': "url('/src/assets/GEL.svg')",
        'kgs': "url('/src/assets/KGS.svg')",
        'tjs': "url('/src/assets/TJS.svg')",
        'tmt': "url('/src/assets/TMT.svg')",
        'sek': "url('/src/assets/SEK.svg')",
        'nok': "url('/src/assets/NOK.svg')",
        'sar': "url('/src/assets/SAR.svg')",
        'qar': "url('/src/assets/QAR.svg')",
        'omr': "url('/src/assets/OMR.svg')",
        'kwd': "url('/src/assets/KWD.svg')",
        'bhd': "url('/src/assets/BHD.svg')",
        'jpy': "url('/src/assets/JPY.svg')",
        'nzd': "url('/src/assets/NZD.svg')",
        'sgd': "url('/src/assets/SGD.svg')",
        'pkr': "url('/src/assets/PKR.svg')",
        'iqd': "url('/src/assets/IQD.svg')",
        'syp': "url('/src/assets/SYP.svg')",
        'afn': "url('/src/assets/AFN.svg')",
        'dkk': "url('/src/assets/DKK.svg')",
        'inr': "url('/src/assets/INR.svg')",
        'krw': "url('/src/assets/KRW.svg')",
        'cad': "url('/src/assets/CAD.svg')",
        'aud': "url('/src/assets/AUD.svg')",
        'chf': "url('/src/assets/CHF.svg')",
        'cny': "url('/src/assets/CNY.svg')",
        'aed': "url('/src/assets/AED.svg')",
        'coin': "url('/src/assets/coin.png')",
        'gold': "url('/src/assets/gold.png')",
      }
    },
  },
  plugins: [],
}